/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package cn.octopus.paperplagiarism.view;

import cn.hutool.core.io.FileUtil;
import cn.hutool.core.util.NumberUtil;
import cn.hutool.core.util.StrUtil;
import cn.octopus.paperplagiarism.constant.Constants;
import cn.octopus.paperplagiarism.vo.InitConfigUtil;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author taoliu
 */
public class SettingView extends javax.swing.JDialog {

    /** Creates new form SettingDialogView
     * @param parent
     * @param modal 
     */
    public SettingView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initComponentsExt();
    }

    private void initComponentsExt() {
        // 计算屏幕的大小  
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
  
        // 计算JFrame的左上角坐标，使得JFrame居中  
        int x = (screenSize.width - getWidth()) / 2;  
        int y = (screenSize.height - getHeight()) / 2;  
        setLocation(x, y); 
        
        threadTF.setText(InitConfigUtil.getConfig("fileConcurrent"));
        thresholdTF.setText(InitConfigUtil.getConfig("defaultSimilarityThreshold"));
        initDirTF.setText(InitConfigUtil.getConfig("initDir"));
        
        URL urlChoise = getClass().getResource("/cn/octopus/paperplagiarism/images/choise.png");
        ImageIcon choiseIcon = new ImageIcon(urlChoise);
        Image choiseImage = choiseIcon.getImage().getScaledInstance(18, 18, Image.SCALE_DEFAULT);
        ImageIcon choiseImageIcon = new ImageIcon(choiseImage);
        initDirBtn.setIcon(choiseImageIcon);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingSaveBtn = new javax.swing.JButton();
        settingCloseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        threadTF = new javax.swing.JTextField();
        thresholdTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        initDirTF = new javax.swing.JTextField();
        initDirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("系统参数设置");
        setLocation(new java.awt.Point(500, 225));
        setPreferredSize(new java.awt.Dimension(400, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 200));

        settingSaveBtn.setText("保存");
        settingSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingSaveBtnActionPerformed(evt);
            }
        });

        settingCloseBtn.setText("关闭");
        settingCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingCloseBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("重复率限定百分比：");

        threadTF.setText("1");

        thresholdTF.setText("75");

        jLabel1.setText("对比文件并发数：");

        jLabel3.setText("初始目录：");

        initDirTF.setEditable(false);

        initDirBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        initDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initDirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingSaveBtn)
                .addGap(34, 34, 34)
                .addComponent(settingCloseBtn)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(initDirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(threadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(thresholdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(threadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thresholdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(initDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(initDirTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingSaveBtn)
                    .addComponent(settingCloseBtn))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingCloseBtnActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING) );
    }//GEN-LAST:event_settingCloseBtnActionPerformed

    private void initDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initDirBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(InitConfigUtil.getConfig("initDir"));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("选择初始化目录");
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (FileUtil.isNotEmpty(file) && FileUtil.isDirectory(file)) {
            initDirTF.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_initDirBtnActionPerformed

    private void settingSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingSaveBtnActionPerformed
        // TODO add your handling code here:
        String fileConcurrent = threadTF.getText();
        String defaultSimilarityThreshold = thresholdTF.getText();
        String initDir = initDirTF.getText();
        List<String> configs = new ArrayList<>();
        if(StrUtil.isBlank(fileConcurrent)){
            fileConcurrent = Constants.FILE_CONCURRENT;
        }
        if(!NumberUtil.isNumber(fileConcurrent)){
            threadTF.setText(Constants.FILE_CONCURRENT);
            fileConcurrent = Constants.FILE_CONCURRENT;
        }
        if(StrUtil.isBlank(defaultSimilarityThreshold)){
            defaultSimilarityThreshold = Constants.DAFAULT_SIMILARITY_THRESHOLD;
        }
        if(!NumberUtil.isNumber(defaultSimilarityThreshold)){
            thresholdTF.setText(Constants.DAFAULT_SIMILARITY_THRESHOLD);
            defaultSimilarityThreshold = Constants.DAFAULT_SIMILARITY_THRESHOLD;
        }
        if(StrUtil.isBlank(initDir)){
            initDir = InitConfigUtil.getConfigFile().getAbsolutePath();
        }
        configs.add("fileConcurrent: "+fileConcurrent);
        configs.add("defaultSimilarityThreshold: "+defaultSimilarityThreshold);
        configs.add("initDir: "+initDir);
        InitConfigUtil.saveConfig(configs);
        JOptionPane.showMessageDialog(null, "配置保存成功！", "消息提示", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_settingSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SettingView dialog = new SettingView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton initDirBtn;
    private javax.swing.JTextField initDirTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton settingCloseBtn;
    private javax.swing.JButton settingSaveBtn;
    private javax.swing.JTextField threadTF;
    private javax.swing.JTextField thresholdTF;
    // End of variables declaration//GEN-END:variables

}
